import numpy as np


class facePoints:
    def __init__(self, marks):
        self.landmarks = marks

    def face_oval(self):
        return np.array(
            [
                self.landmarks[10],
                self.landmarks[338],
                self.landmarks[338],
                self.landmarks[297],
                self.landmarks[297],
                self.landmarks[332],
                self.landmarks[332],
                self.landmarks[284],
                self.landmarks[284],
                self.landmarks[251],
                self.landmarks[251],
                self.landmarks[389],
                self.landmarks[389],
                self.landmarks[356],
                self.landmarks[356],
                self.landmarks[454],
                self.landmarks[454],
                self.landmarks[323],
                self.landmarks[323],
                self.landmarks[361],
                self.landmarks[361],
                self.landmarks[288],
                self.landmarks[288],
                self.landmarks[397],
                self.landmarks[397],
                self.landmarks[365],
                self.landmarks[379],
                self.landmarks[378],
                self.landmarks[378],
                self.landmarks[400],
                self.landmarks[400],
                self.landmarks[377],
                self.landmarks[377],
                self.landmarks[152],
                self.landmarks[152],
                self.landmarks[148],
                self.landmarks[148],
                self.landmarks[176],
                self.landmarks[176],
                self.landmarks[149],
                self.landmarks[149],
                self.landmarks[150],
                self.landmarks[150],
                self.landmarks[136],
                self.landmarks[136],
                self.landmarks[172],
                self.landmarks[172],
                self.landmarks[58],
                self.landmarks[58],
                self.landmarks[132],
                self.landmarks[132],
                self.landmarks[93],
                self.landmarks[93],
                self.landmarks[234],
                self.landmarks[234],
                self.landmarks[127],
                self.landmarks[127],
                self.landmarks[162],
                self.landmarks[162],
                self.landmarks[21],
                self.landmarks[21],
                self.landmarks[54],
                self.landmarks[54],
                self.landmarks[103],
                self.landmarks[103],
                self.landmarks[67],
                self.landmarks[67],
                self.landmarks[109],
                self.landmarks[109],
                self.landmarks[10],

            ],
            dtype="float32",
        )

    def left_eye(self):
        return np.array(
            [
                self.landmarks[263],
                self.landmarks[249],
                self.landmarks[249],
                self.landmarks[390],
                self.landmarks[390],
                self.landmarks[373],
                self.landmarks[374],
                self.landmarks[380],
                self.landmarks[380],
                self.landmarks[381],
                self.landmarks[381],
                self.landmarks[382],
                self.landmarks[382],
                self.landmarks[362],
                self.landmarks[263],
                self.landmarks[466],
                self.landmarks[466],
                self.landmarks[388],
                self.landmarks[388],
                self.landmarks[387],
                self.landmarks[387],
                self.landmarks[386],
                self.landmarks[386],
                self.landmarks[385],
                self.landmarks[385],
                self.landmarks[384],
                self.landmarks[384],
                self.landmarks[398],
                self.landmarks[398],
                self.landmarks[362],

            ],
            dtype="float32",
        )

    def right_eye(self):
        return np.array(
            [
                self.landmarks[33],
                self.landmarks[7],
                self.landmarks[7],
                self.landmarks[163],
                self.landmarks[144],
                self.landmarks[144],
                self.landmarks[145],
                self.landmarks[153],
                self.landmarks[153],
                self.landmarks[154],
                self.landmarks[154],
                self.landmarks[155],
                self.landmarks[155],
                self.landmarks[133],
                self.landmarks[133],
                self.landmarks[246],
                self.landmarks[246],
                self.landmarks[161],
                self.landmarks[161],
                self.landmarks[160],
                self.landmarks[160],
                self.landmarks[159],
                self.landmarks[159],
                self.landmarks[158],
                self.landmarks[158],
                self.landmarks[157],
                self.landmarks[157],
                self.landmarks[173],
                self.landmarks[173],
                self.landmarks[133],

            ],
            dtype="float32",
        )

    def left_eye_brow(self):
        return np.array(
            [
                self.landmarks[276],
                self.landmarks[283],
                self.landmarks[283],
                self.landmarks[282],
                self.landmarks[282],
                self.landmarks[295],
                self.landmarks[295],
                self.landmarks[285],
                self.landmarks[300],
                self.landmarks[293],
                self.landmarks[293],
                self.landmarks[334],
                self.landmarks[334],
                self.landmarks[296],
                self.landmarks[296],
                self.landmarks[336],

            ],
            dtype="float32",
        )

    def right_eye_brow(self):
        return np.array(
            [
                self.landmarks[46],
                self.landmarks[53],
                self.landmarks[53],
                self.landmarks[52],
                self.landmarks[65],
                self.landmarks[55],
                self.landmarks[70],
                self.landmarks[63],
                self.landmarks[63],
                self.landmarks[105],
                self.landmarks[105],
                self.landmarks[66],
                self.landmarks[66],
                self.landmarks[107],
            ],
            dtype="float32",
        )
